'use client';
import {jobSchema} from '../lib/validation';
import ExtractJob from './extract-job';
import SalaryEditor from './salary-editor';
import {useState} from 'react';
import {ExternalLink,Save,ArrowRight} from 'lucide-react';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Checkbox} from '@/components/ui/checkbox';
import {Job,statuses,docNames,documentProgress} from '@/lib/opportunities';
export function Choice({label,value,values,onChange}:{label:string;value:string;values:readonly string[];onChange:(s:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue/></SelectTrigger><SelectContent>{values.map(v=><SelectItem key={v} value={v}>{v}</SelectItem>)}</SelectContent></Select>;}
export default function Editor({job,jobs,isNew,onSave,onDirty}:{job:Job;jobs:Job[];isNew:boolean;onSave:(j:Job)=>Promise<void>;onDirty:()=>void}){
const original=documentProgress(job);
const [draft,setDraft]=useState(job),[busy,setBusy]=useState(false),[error,setError]=useState(''),[step,setStep]=useState(['Submitted','Waiting for Recommendation','Interview','Offer','Rejected','Declined','Withdrawn'].includes(job.status)?'5':original.unchecked?'2':original.done<original.total?'3':'4');
function replace(next:Job){onDirty();setDraft(next);}
function change(k:keyof Job,v:string){onDirty();setDraft(d=>({...d,[k]:v}));}
function doc(name:string,state:Job['docs'][string]){onDirty();setDraft(d=>({...d,docs:{...d.docs,[name]:state}}));}
async function submit(e:React.FormEvent){e.preventDefault();if(!draft.title.trim()&&!draft.url.trim()){setError('Enter a job title or a posting link.');setStep('1');return;}const validated=jobSchema.safeParse(draft);if(!validated.success){setError(validated.error.issues.map(i=>i.path.join('.')+': '+i.message).join('; '));setStep('1');return;}setBusy(true);setError('');try{await onSave(draft);}catch(e){setError(e instanceof Error?e.message:'Could not save. Please try again.');}finally{setBusy(false);}}
function field(k:keyof Job,label:string,placeholder='',type='text'){return <label className="field" key={k}><span>{label}</span><Input type={type} value={String(draft[k])} placeholder={placeholder} maxLength={k==='url'?4000:500} onChange={e=>change(k,e.target.value)}/></label>;}
const progress=documentProgress(draft),required=docNames.filter(n=>['Required','In progress','Done'].includes(draft.docs[n]));
const posting=draft.url&&/^https?:\/\//i.test(draft.url)?<a className="secondary" href={draft.url} target="_blank" rel="noopener noreferrer">Open posting<ExternalLink size={15}/></a>:<p className="form-note">Add a posting link in Details.</p>;
const notes=<label className="field"><span>Notes</span><Textarea value={draft.notes} maxLength={10000} onChange={e=>change('notes',e.target.value)} placeholder="Requirements, contact details, or follow-up notes"/></label>;
const core=<>{field('url','Posting link','https://…','url')}<ExtractJob job={draft} onChange={replace}/>{field('title','Job / program title','e.g. PhD in Remote Sensing')}</>;
const details=<><div className="form-grid">{field('organization','Organization / university')}<label className="field"><span>Type</span><Choice label="Opportunity type" value={draft.type} values={['PhD','Industry','Postdoc','Other']} onChange={v=>change('type',v)}/></label>{field('deadline','Application deadline','','date')}{field('found','Date found','','date')}{field('location','Location')}{field('country','Country')}{field('start','Start date','YYYY-MM-DD or as advertised')}</div>{field('team','Department, advisor or team')}<SalaryEditor job={draft} jobs={jobs} onChange={replace}/>{notes}</>;
return <form onSubmit={submit} className="edit-form"><fieldset disabled={busy}>
{isNew?<>{core}<details className="more-details"><summary>Optional details</summary>{details}</details></>:<Tabs value={step} onValueChange={setStep} className="editor-tabs"><TabsList className="step-tabs">{['Details','Requirements','Documents','Apply','Response'].map((name,i)=><TabsTrigger key={name} value={String(i+1)} className="step-tab"><span>{i+1}</span>{name}</TabsTrigger>)}</TabsList>
<TabsContent value="1"><div className="step-heading"><h3>1. Job details</h3></div>{core}{details}<button type="button" className="next-button" onClick={()=>setStep('2')}>Next: Check requirements<ArrowRight size={15}/></button></TabsContent>
<TabsContent value="2"><div className="step-heading"><h3>2. Check requirements</h3><p>Open the posting and confirm which documents are required.</p></div>{posting}<div className="requirement-list">{docNames.map(n=><div key={n} className="requirement-row"><span>{n}</span><Choice label={n+' requirement'} value={draft.docs[n]==='Not checked'?'Not checked':draft.docs[n]==='Not required'?'Not required':'Required'} values={['Not checked','Required','Not required']} onChange={v=>{if(v==='Required'&&['Done','In progress'].includes(draft.docs[n]))return;doc(n,v as Job['docs'][string]);}}/></div>)}</div>{progress.unchecked&&<p className="inline-warning">Some requirements still need checking.</p>}<button type="button" className="next-button" onClick={()=>setStep('3')}>Next: Prepare documents<ArrowRight size={15}/></button></TabsContent>
<TabsContent value="3"><div className="step-heading"><h3>3. Prepare documents</h3><p>{progress.done} of {progress.total} required documents complete.</p></div>{progress.unchecked&&<div className="inline-warning">Requirements are not fully checked. <button type="button" onClick={()=>setStep('2')}>Review requirements</button></div>}{required.length?required.map(n=><label className={'document-check '+(draft.docs[n]==='Done'?'complete':'')} key={n}><Checkbox aria-label={'Mark '+n+' done'} checked={draft.docs[n]==='Done'} onCheckedChange={checked=>doc(n,checked?'Done':'Required')}/><span>{n}</span><small>{draft.docs[n]==='Done'?'Complete':draft.docs[n]==='In progress'?'In progress':'To do'}</small></label>):<p className="form-note">{progress.unchecked?'Confirm requirements in step 2 to create this checklist.':'No documents are required.'}</p>}<button type="button" className="next-button" onClick={()=>setStep('4')}>Next: Apply<ArrowRight size={15}/></button></TabsContent>
<TabsContent value="4"><div className="step-heading"><h3>4. Submit application</h3><p>Submit on the employer’s website, then record it here.</p></div>{posting}{(progress.unchecked||progress.done<progress.total)&&<p className="inline-warning">Your document checklist is incomplete. You can still record an application already submitted.</p>}<label className="document-check submitted-check"><Checkbox aria-label="I have submitted this application" checked={['Submitted','Waiting for Recommendation','Interview','Offer','Rejected'].includes(draft.status)} onCheckedChange={checked=>{change('status',checked?'Submitted':'Preparing');if(checked&&!draft.applied)change('applied',new Date().toLocaleDateString('en-CA'));}}/><span>I have submitted this application</span></label>{field('applied','Date applied','','date')}<p className="form-note">This updates your tracker. It does not submit an application for you.</p></TabsContent>
<TabsContent value="5"><div className="step-heading"><h3>5. Track response</h3><p>Update the status when you hear back.</p></div><label className="field"><span>Application status</span><Choice label="Application status" value={draft.status} values={statuses} onChange={v=>{change('status',v);if(v==='Submitted'&&!draft.applied)change('applied',new Date().toLocaleDateString('en-CA'));}}/></label>{field('applied','Date applied','','date')}{notes}</TabsContent>
</Tabs>}
{error&&<div role="alert" className="error-box">{error}</div>}<div className="editor-actions"><span>{isNew?'Step 1 of 5':'Changes are saved when you click Save.'}</span><button className="primary" type="submit" disabled={busy}><Save size={16}/>{busy?'Saving…':isNew?'Save job':'Save changes'}</button></div></fieldset></form>;
}
