import {useEffect,useRef,useState} from 'react';
import {supabase} from '../src/supabase';
import {extractText,extractStructured,type Extracted} from '../lib/extraction';
import type {Job} from '../lib/opportunities';
import {netLabel} from '../lib/salary';
export default function ExtractJob({job,onChange}:{job:Job;onChange:(job:Job)=>void}){
  const [text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Extracted|null>(null),[selected,setSelected]=useState<string[]>([]),[fallback,setFallback]=useState(false);const request=useRef(0);const latest=useRef(job);latest.current=job;
  useEffect(()=>{request.current++;setResult(null);setError('');setBusy(false);},[job.url]);
  function preview(r:Extracted){setResult(r);setSelected(Object.keys(r.fields).filter(k=>!latest.current[k as keyof Job]).concat(r.salary&&!latest.current.salary&&!latest.current.salaryDetails?['salary']:[]));if(!Object.keys(r.fields).length&&!r.salary&&!r.requirements.length)setError('No recognizable fields found. Add details manually or paste labelled fields such as “Organization: …”.');}
  async function extractLink(){const id=++request.current;setBusy(true);setError('');setResult(null);try{const url=new URL(job.url);if(url.protocol!=='https:')throw Error('Use an HTTPS posting link.');if(!supabase)throw Error('Sign in to extract a posting.');const {data,error}=await supabase.functions.invoke('extract-job',{body:{url:url.href}});if(error?.context instanceof Response){const problem=await error.context.json().catch(()=>null);if(problem?.error)throw Error(problem.error);}if(error||data?.error)throw Error(data?.error||'Link extraction is unavailable. Paste the posting text below; the website may block access or the extraction service may need setup.');if(id===request.current)preview(extractStructured(data.structured,data.text));}catch(e){if(id===request.current){setError(e instanceof Error?e.message:'Could not read the posting.');setFallback(true);}}finally{if(id===request.current)setBusy(false);}}
  function toggle(key:string){setSelected(s=>s.includes(key)?s.filter(k=>k!==key):[...s,key]);}
  function apply(){if(!result)return;const next={...job,docs:{...job.docs}};for(const [k,v] of Object.entries(result.fields))if(selected.includes(k))(next as any)[k]=v;if(selected.includes('salary')&&result.salary){next.salaryDetails=result.salary;next.salary=netLabel(result.salary);}for(const doc of result.requirements)if(selected.includes('doc:'+doc)&&!['Done','In progress'].includes(next.docs[doc]))next.docs[doc]='Required';onChange(next);setResult(null);setError('Selected details added. Review the form, then save.');}
  return <section className="extract-panel"><div className="extract-actions"><button type="button" className="primary" disabled={busy||!job.url} onClick={()=>void extractLink()}>{busy?'Reading posting…':'Extract from link'}</button><button type="button" className="text-button" onClick={()=>setFallback(!fallback)}>Paste description instead</button></div>{fallback&&<><label className="field"><span>Job description</span><textarea maxLength={80000} value={text} onChange={e=>setText(e.target.value)} placeholder="Paste the job posting here. This text is processed on your device."/></label><button type="button" className="secondary" disabled={!text.trim()||busy} onClick={()=>{setError('');preview(extractText(text));}}>Extract pasted text</button></>}{error&&<p role="status" className="inline-warning">{error}</p>}{result&&<div className="extraction-review"><h3>Review extracted details</h3><p>Existing values are unchecked. Check a field to replace it. Requirements are suggestions to verify.</p>{result.notices?.map(notice=><p key={notice} className="inline-warning">{notice}</p>)}{Object.entries(result.fields).map(([key,value])=><label key={key}><input type="checkbox" checked={selected.includes(key)} onChange={()=>toggle(key)}/><span><strong>{key}</strong>{value}</span></label>)}{result.salary&&<label><input type="checkbox" checked={selected.includes('salary')} onChange={()=>toggle('salary')}/><span><strong>Salary from posting · {result.salary.basis.toLowerCase()}</strong>{result.salary.currency} {result.salary.min}–{result.salary.max} / {result.salary.period.toLowerCase()}<small>{result.salary.evidence}</small></span></label>}{result.requirements.map(doc=><label key={doc}><input type="checkbox" disabled={['Done','In progress'].includes(job.docs[doc])} checked={selected.includes('doc:'+doc)} onChange={()=>toggle('doc:'+doc)}/><span>Requires {doc}{['Done','In progress'].includes(job.docs[doc])?' (progress preserved)':''}</span></label>)}<button type="button" className="secondary" disabled={!selected.length} onClick={apply}>Use selected details</button></div>}</section>;
}
