import {useState} from 'react';
import type {Job} from '../lib/opportunities';
import {comparableEstimate,netLabel,salarySource,type SalaryDetails} from '../lib/salary';
import {extractText} from '../lib/extraction';
const blank:SalaryDetails={source:'Posted',basis:'Unknown',min:0,max:0,currency:'EUR',period:'Month',evidence:''};
export default function SalaryEditor({job,jobs,onChange}:{job:Job;jobs:Job[];onChange:(job:Job)=>void}){
  const [message,setMessage]=useState('');const s=job.salaryDetails;
  function update(next:SalaryDetails){onChange({...job,salaryDetails:next,salary:netLabel(next)});}
  function guess(){
    const estimate=comparableEstimate(job,jobs,value=>extractText('Net salary: '+value).salary);
    if(!estimate){setMessage('No comparable net salaries in your tracker for this country and job type. Enter an estimate and its source below.');return;}
    update(estimate);setMessage('Estimate added for review. This uses your own comparable entries, not market salary data.');
  }
  const input=(key:'min'|'max'|'deductions'|'hoursPerWeek'|'paymentsPerYear',label:string)=><label className="field"><span>{label}</span><input type="number" min={key==='deductions'?0:1} max={key==='deductions'?99.99:key==='hoursPerWeek'?168:key==='paymentsPerYear'?24:100000000} step="any" value={s?.[key]??''} onChange={e=>{const v=e.target.value===''?undefined:Number(e.target.value);const next={...s!,[key]:v};if(key==='min'&&(!s!.max||s!.max===s!.min))next.max=v??0;update(next as SalaryDetails);}}/></label>;
  const select=(key:'source'|'basis'|'period',label:string,values:string[])=><label className="field"><span>{label}</span><select value={s![key]} onChange={e=>update({...s!,[key]:e.target.value})}>{values.map(v=><option key={v}>{v}</option>)}</select></label>;
  return <section className="salary-panel"><h3>Net salary</h3><p className="form-note">Monthly take-home pay. Estimates are labelled in the applications table.</p>{!s?<><label className="field"><span>Net salary as recorded</span><input maxLength={500} value={job.salary} placeholder="e.g. EUR 2,100 / month" onChange={e=>onChange({...job,salary:e.target.value})}/></label><button type="button" className="secondary" onClick={()=>update(extractText('Net salary: '+job.salary).salary||blank)}>Add salary source / calculate net</button><p className="form-note">Existing entries keep “Source not recorded” until you confirm the source.</p></>:<><div className="form-grid">{select('source','Salary source',['Posted','Guessed'])}{select('basis','Amount in the source',['Unknown','Gross','Net'])}{input('min','Amount / lower end')}{input('max','Upper end') }<label className="field"><span>Currency</span><input maxLength={3} value={s.currency} onChange={e=>update({...s,currency:e.target.value.toUpperCase().replace(/[^A-Z]/g,'')})}/></label>{select('period','Pay period',['Year','Month','Week','Hour'])}{s.period==='Month'&&input('paymentsPerYear','Payments per year (default 12)')}{s.period==='Hour'&&input('hoursPerWeek','Paid hours per week')}{s.basis==='Gross'&&input('deductions','Estimated total deductions (%)')}</div><label className="field"><span>Source / assumptions</span><textarea maxLength={1000} value={s.evidence} placeholder="Posting excerpt, comparable role, or tax calculator assumptions" onChange={e=>update({...s,evidence:e.target.value})}/></label><div className="salary-result"><strong>{netLabel(s)||'Net pay needs more information'}</strong><span className="salary-source">{salarySource(job)}</span></div>{s.basis==='Unknown'&&<p className="inline-warning">Confirm whether the posting means gross or net pay.</p>}{s.basis==='Gross'&&<p className="inline-warning">Approximate net = annual gross × (1 − deductions %) ÷ 12. Enter total employee tax and social deductions for your situation. This is not a country-specific tax calculation.</p>}<button type="button" className="text-button" onClick={()=>onChange({...job,salaryDetails:undefined,salary:''})}>Clear salary</button><p className="form-note">Annual average across 12 months; individual payslips may differ. No currency conversion.</p></> }<button type="button" className="text-button" onClick={guess}>Estimate from my similar jobs</button>{message&&<p role="status" className="inline-warning">{message}</p>}</section>;
}
