import {extractText} from '../lib/extraction';
import {monthlyNet,salarySource} from '../lib/salary';
import {useState,useEffect,useRef,Fragment} from 'react';
import Editor from './editor';
import {api} from '../src/data';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {blankDocs,docNames} from '@/lib/opportunities';
import {ArrowUpRight,ArrowRight,ArrowUpDown,ChevronUp,ChevronDown,Plus,Search,LayoutDashboard,BriefcaseBusiness,CalendarDays,Files,Smartphone,Sprout,Check,Bookmark,Send,Globe2,ChevronRight,Circle,Columns3} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Progress} from '@/components/ui/progress';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {DropdownMenu,DropdownMenuContent,DropdownMenuCheckboxItem,DropdownMenuTrigger} from '@/components/ui/dropdown-menu';
import {Job,closed,needsApplication,dateLabel,daysLeft,documentProgress} from '@/lib/opportunities';
const sections=[{name:'Dashboard',icon:LayoutDashboard},{name:'Applications',icon:BriefcaseBusiness},{name:'Deadlines',icon:CalendarDays},{name:'Documents',icon:Files}];
export default function Tracker({email,onSignOut}:{email:string;onSignOut:()=>void}){
const [jobs,setJobs]=useState<Job[]>([]),[view,setView]=useState('Dashboard'),[search,setSearch]=useState(''),[filter,setFilter]=useState('All');
const [sort,setSort]=useState<{key:SortKey;direction:'asc'|'desc'}>({key:'deadline',direction:'asc'}),[groupBy,setGroupBy]=useState<GroupKey>('none'),[columns,setColumns]=useState<Record<ColumnKey,boolean>>({status:true,deadline:true,next:true,salary:true,salarySource:true,documents:false,location:false,country:false,type:false});
const [loading,setLoading]=useState(true),[error,setError]=useState(''),[capture,setCapture]=useState<Job|null>(null),[selected,setSelected]=useState<Job|null>(null),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false),[refresh,setRefresh]=useState(0),[savingId,setSavingId]=useState('');
const busyRef=useRef(false);
useEffect(()=>{let alive=true;const controller=new AbortController();async function load(){try{const r=await api('/api/jobs',{cache:'no-store',signal:controller.signal});const data=await r.json() as {jobs:Job[];error?:string};if(!r.ok)throw Error(data.error||'Could not load your opportunities.');if(alive){setJobs(data.jobs);setError('');}}catch(e){if(alive)setError(e instanceof Error?e.message:'Could not connect.');}finally{if(alive)setLoading(false);}}if(!capture&&!selected){void load();const focus=()=>{if(!document.hidden)void load();};window.addEventListener('focus',focus);const timer=setInterval(focus,30000);return()=>{alive=false;controller.abort();window.removeEventListener('focus',focus);clearInterval(timer);};}return()=>{alive=false;controller.abort();};},[capture,selected,refresh]);
function newCapture(){setDirty(false);setCapture({id:crypto.randomUUID(),title:'',url:'',organization:'',type:'PhD',team:'',location:'',country:'',found:new Date().toLocaleDateString('en-CA'),status:'Saved',deadline:'',applied:'',salary:'',start:'',notes:'',docs:blankDocs(),version:1});}
function openJob(j:Job){setDirty(false);setSelected(j);}
function closeEditor(){if(busyRef.current)return;if(dirty){setDiscard(true);return;}setSelected(null);setCapture(null);}
async function persist(j:Job,create=false){const r=await api('/api/jobs',{method:create?'POST':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(j)});const d=await r.json() as {job:Job;error?:string};if(!r.ok)throw Error(d.error||'Could not save your opportunity.');setJobs(list=>create?[d.job,...list]:list.map(item=>item.id===j.id?d.job:item));return d.job as Job;}
async function save(j:Job){busyRef.current=true;try{await persist(j,!!capture);setDirty(false);setSelected(null);setCapture(null);toast.success(capture?'Job saved.':'Changes saved.');}finally{busyRef.current=false;}}
async function completeNext(j:Job){const next=docNames.find(n=>['Required','In progress'].includes(j.docs[n]));if(!next)return;setSavingId(j.id);try{await persist({...j,docs:{...j.docs,[next]:'Done'}});toast.success(next+' marked complete.');}catch(e){toast.error(e instanceof Error?e.message:'Could not save.');}finally{setSavingId('');}}
useEffect(()=>{if('serviceWorker' in navigator)navigator.serviceWorker.register(import.meta.env.BASE_URL+'sw.js').catch(()=>{});if(new URLSearchParams(location.search).has('capture')){newCapture();history.replaceState(null,'',location.pathname);}const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context)return;const controller=new AbortController();try{Promise.resolve(context.registerTool({name:'start_opportunity_capture',description:'Open the quick-save form. This does not save an opportunity; the user completes the form.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty object');newCapture();return {opened:true,saved:false};}},{signal:controller.signal})).catch(()=>{});}catch{}return()=>controller.abort();},[]);
const [stepFilter,setStepFilter]=useState(0);
const active=jobs.filter(j=>!closed(j)),upcoming=jobs.filter(j=>needsApplication(j)&&j.deadline).sort((a,b)=>a.deadline.localeCompare(b.deadline));
const pending=active.filter(needsApplication).sort((a,b)=>(a.deadline||"9999").localeCompare(b.deadline||"9999"));const nextJob=pending[0];
const filtered=jobs.filter(j=>(!stepFilter||(!closed(j)&&stage(j)===stepFilter))&&(filter==='All'||filter==='Active'&&!closed(j)||filter==='Submitted'&&['Submitted','Waiting for Recommendation'].includes(j.status)||filter==='Closed'&&closed(j))&&[j.title,j.organization,j.country,j.location].join(' ').toLowerCase().includes(search.toLowerCase()));
const sorted=[...filtered].sort((a,b)=>compareJobs(a,b,sort.key)*(sort.direction==='asc'?1:-1));
const grouped=groupJobs(sorted,groupBy);
return <SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}>
<Sidebar className="app-sidebar"><SidebarHeader><div className="brand"><span className="brand-mark">JT</span>Job Tracker</div></SidebarHeader><SidebarContent><AppNavigation view={view} count={jobs.length} onNavigate={name=>{setView(name);setStepFilter(0);}}/></SidebarContent><SidebarFooter><button className="phone-link" onClick={()=>setView('iPhone setup')}><Smartphone size={18}/>Install on iPhone<ArrowUpRight size={16}/></button><div className="profile"><span className="avatar">ME</span><div><span title={email}>{email}</span><small>Private · Synced across devices</small><button onClick={onSignOut}>Sign out</button></div></div></SidebarFooter></Sidebar>
<main className="main"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu"/><span>Workspace</span><ChevronRight size={14}/><strong>{view}</strong></div><button className="sync-button" onClick={()=>setRefresh(n=>n+1)}>Refresh</button></header>
<div className="page">{error&&<div className="error-box" role="alert">{error}<button onClick={()=>setRefresh(n=>n+1)}>Retry</button><button onClick={onSignOut}>Sign out</button></div>}
<div className="page-heading"><div><h1>{view}</h1><p className="subtitle">{view==='Dashboard'?'Your next task, deadlines, and application progress.':view==='Applications'?active.length+' active · '+jobs.filter(closed).length+' closed':view==='Documents'?'Track required documents for each active application.':view==='Deadlines'?'Application deadlines, ordered by date.':'Use the same tracker on your phone.'}</p></div><button className="primary" onClick={newCapture}><Plus size={18}/>Save job</button></div>
{loading?<div className="loading-note" role="status">Loading applications…</div>:<>
{view==='Dashboard'&&<>
<section className={'next-task '+(nextJob?urgency(nextJob):'normal')}><div className="next-task-main"><span className="task-label">NEXT ACTION</span><h2>{nextJob?actionLabel(nextJob):'No pending application tasks'}</h2>{nextJob&&<p><strong>{nextJob.title||'Saved posting'}</strong><span>{nextJob.organization}</span></p>}</div><div className="next-task-side">{nextJob?.deadline&&<Due job={nextJob}/>}<button className="primary" onClick={()=>nextJob?openJob(nextJob):newCapture()}>{nextJob?stage(nextJob)===2?'Check requirements':stage(nextJob)===3?'Prepare documents':'Review & apply':'Save a job'}<ArrowRight size={17}/></button></div></section>
<section className="workflow-section"><div className="section-title"><h2>Application workflow</h2><span>Pick a step to continue</span></div><div className="workflow">{stepNames.map((label,i)=><button key={label} className={'workflow-step step-'+(i+1)} onClick={()=>{if(i===0){newCapture();return;}setStepFilter(i+1);setFilter('All');setSearch('');setView('Applications');}}><span className="step-number">{i+1}</span><span className="step-name">{label}</span><strong>{i===0?<Plus size={18}/>:active.filter(j=>stage(j)===i+1).length}</strong></button>)}</div></section>
<div className="work-grid"><section className="work-panel"><div className="section-title"><h2>To do <span className="count">{pending.length}</span></h2><button className="text-button" onClick={()=>setView('Documents')}>Checklists<ArrowRight size={14}/></button></div>{!pending.length&&<div className="empty">No pending tasks. Submitted applications are under Track response.</div>}{pending.slice(0,3).map(j=><button key={j.id} className="assignment" onClick={()=>openJob(j)}><span className={'assignment-step step-'+stage(j)}>{stage(j)}</span><span className="assignment-text"><strong>{actionLabel(j)}</strong><span>{j.title||'Saved posting'}</span></span><div className="assignment-meta"><Due job={j}/><ArrowUpRight size={16}/></div></button>)}</section>
<section className="work-panel"><div className="section-title"><h2>Upcoming deadlines</h2><CalendarDays size={18}/></div>{!upcoming.length&&<div className="empty">No open applications with deadlines.</div>}{upcoming.slice(0,3).map(j=><button className="deadline-item" key={j.id} onClick={()=>openJob(j)}><span className={'date-tile '+urgency(j)}><small>{new Date(j.deadline+'T12:00:00').toLocaleDateString('en',{month:'short'})}</small><strong>{j.deadline.slice(8)}</strong></span><span className="deadline-text"><strong>{j.title||'Saved posting'}</strong><Due job={j}/></span><ArrowUpRight size={16}/></button>)}<button className="text-button" onClick={()=>setView('Deadlines')}>View deadlines<ArrowRight size={14}/></button></section></div>
</>}
{(view==='Dashboard'||view==='Applications')&&<section className="opportunities"><div className="section-title"><h2>Applications <span className="count">{jobs.length}</span></h2>{stepFilter>0&&<button className="text-button" onClick={()=>setStepFilter(0)}>Step {stepFilter}: {stepNames[stepFilter-1]} ×</button>}</div><div className="table-toolbar"><div className="filter-buttons">{['All','Active','Submitted','Closed'].map(f=><button key={f} className={filter===f?'selected':''} onClick={()=>setFilter(f)}>{f}</button>)}</div><div className="table-controls"><label className="search"><Search size={17}/><input placeholder="Search applications" aria-label="Search applications" value={search} onChange={e=>setSearch(e.target.value)}/></label><Select value={sort.key} onValueChange={v=>setSort({key:v as SortKey,direction:'asc'})}><SelectTrigger className="sort-select" aria-label="Sort applications"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="deadline">Sort: Deadline</SelectItem><SelectItem value="title">Sort: Position</SelectItem><SelectItem value="status">Sort: Status</SelectItem><SelectItem value="next">Sort: Next step</SelectItem><SelectItem value="documents">Sort: Documents</SelectItem><SelectItem value="location">Sort: Location</SelectItem><SelectItem value="country">Sort: Country</SelectItem><SelectItem value="type">Sort: Type</SelectItem><SelectItem value="salary">Sort: Net salary (by currency)</SelectItem><SelectItem value="salarySource">Sort: Salary source</SelectItem></SelectContent></Select><button className="sort-direction" aria-label={sort.direction==='asc'?'Sort descending':'Sort ascending'} onClick={()=>setSort(current=>({...current,direction:current.direction==='asc'?'desc':'asc'}))}>{sort.direction==='asc'?<ChevronUp size={16}/>:<ChevronDown size={16}/>}</button><Select value={groupBy} onValueChange={v=>setGroupBy(v as GroupKey)}><SelectTrigger className="group-select" aria-label="Group applications"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No grouping</SelectItem><SelectItem value="status">Group by status</SelectItem><SelectItem value="step">Group by next step</SelectItem><SelectItem value="country">Group by country</SelectItem><SelectItem value="deadline">Group by urgency</SelectItem></SelectContent></Select><DropdownMenu><DropdownMenuTrigger className="columns-button"><Columns3 size={16}/>Columns</DropdownMenuTrigger><DropdownMenuContent align="end">{columnOptions.map(c=><DropdownMenuCheckboxItem key={c.key} checked={columns[c.key]} onCheckedChange={checked=>setColumns(prev=>({...prev,[c.key]:Boolean(checked)}))}>{c.label}</DropdownMenuCheckboxItem>)}</DropdownMenuContent></DropdownMenu></div></div>
<Table><TableHeader><TableRow><SortHead label="POSITION / ORGANIZATION" sortKey="title" sort={sort} setSort={setSort}/>{columns.status&&<SortHead label="STATUS" sortKey="status" sort={sort} setSort={setSort}/>}{columns.deadline&&<SortHead label="DEADLINE" sortKey="deadline" sort={sort} setSort={setSort}/>}{columns.salary&&<SortHead label="NET SALARY" sortKey="salary" sort={sort} setSort={setSort}/>}{columns.salarySource&&<SortHead label="SALARY SOURCE" sortKey="salarySource" sort={sort} setSort={setSort}/>}{columns.next&&<SortHead label="NEXT STEP" sortKey="next" sort={sort} setSort={setSort}/>}{columns.documents&&<SortHead label="DOCUMENTS" sortKey="documents" sort={sort} setSort={setSort}/>}{columns.location&&<SortHead label="LOCATION" sortKey="location" sort={sort} setSort={setSort}/>}{columns.country&&<SortHead label="COUNTRY" sortKey="country" sort={sort} setSort={setSort}/>}{columns.type&&<SortHead label="TYPE" sortKey="type" sort={sort} setSort={setSort}/>}<TableHead/></TableRow></TableHeader><TableBody>{Object.entries(grouped).map(([label,rows])=><Fragment key={label}>{groupBy!=='none'&&<TableRow className="group-row"><TableCell colSpan={2+Object.values(columns).filter(Boolean).length}><strong>{label}</strong><span>{rows.length}</span></TableCell></TableRow>}{rows.map(j=><ApplicationRow key={j.id} job={j} columns={columns} openJob={openJob}/>)}</Fragment>)}</TableBody></Table>{!filtered.length&&<div className="empty">No applications match these filters.</div>}<div className="table-footer"><span>{filtered.length} of {jobs.length} applications</span><span>Click headings to sort. On phones, swipe the table.</span></div></section>}
{view==='Deadlines'&&<div className="simple-list"><p className="form-note">Urgency applies to jobs you haven’t submitted. Submitted applications are shown for reference.</p>{!active.some(j=>j.deadline)&&<div className="empty">No deadlines added.</div>}{active.filter(j=>j.deadline).sort((a,b)=>a.deadline.localeCompare(b.deadline)).map(j=><article key={j.id} className={'deadline-row '+urgency(j)}><CalendarDays/><div><button className="list-title" onClick={()=>openJob(j)}>{j.title||'Saved posting'}</button><p>{j.organization}</p></div><div className="date-detail"><strong>{dateLabel(j.deadline)}</strong><Due job={j}/></div><button className="secondary" onClick={()=>openJob(j)}>Open<ArrowUpRight size={15}/></button></article>)}</div>}
{view==='Documents'&&<div className="simple-list">{!active.length&&<div className="empty">No active applications.</div>}{active.map(j=><article key={j.id} className="document-card"><Files/><div><button className="list-title" onClick={()=>openJob(j)}>{j.title||'Saved posting'}</button><p>{j.organization}</p><p className="next-label">{documentProgress(j).unchecked?'Check the posting to confirm requirements.':nextStep(j)}</p></div><DocsProgress job={j}/><button className="secondary" onClick={()=>openJob(j)}>Open checklist<ArrowUpRight size={15}/></button>{!documentProgress(j).unchecked&&documentProgress(j).done<documentProgress(j).total&&<button className="primary" disabled={!!savingId} onClick={()=>completeNext(j)}><Check size={16}/>{savingId===j.id?'Saving…':'Mark next done'}</button>}</article>)}</div>}
{view==='iPhone setup'&&<section className="install-card"><h2>Install on iPhone</h2><ol><li>Open this website in Safari.</li><li>Tap Share, then Add to Home Screen.</li><li>Sign in with the same account you use on your computer.</li></ol><h3>Save a job from your phone</h3><p>Copy the posting link, open Job Tracker, tap Save job, and paste the link.</p><p>An internet connection is required to load and save applications.</p></section>}
</>}<footer className="page-footer"><span>Private workspace</span><button onClick={()=>setRefresh(n=>n+1)}>Refresh data</button></footer></div></main>
<Dialog open={!!capture} onOpenChange={open=>{if(!open)closeEditor();}}><DialogContent className="capture-dialog"><DialogHeader><DialogTitle>Save job</DialogTitle><DialogDescription>Step 1 · Add a link or title. Other details are optional.</DialogDescription></DialogHeader>{capture&&<Editor key={capture.id} job={capture} jobs={jobs} isNew onDirty={()=>setDirty(true)} onSave={save}/>}</DialogContent></Dialog>
<Sheet open={!!selected} onOpenChange={open=>{if(!open)closeEditor();}}><SheetContent className="detail-sheet"><SheetHeader><SheetTitle>{selected?.title||'Saved job'}</SheetTitle><SheetDescription>{selected?.organization||'Application details'}</SheetDescription></SheetHeader>{selected&&<Editor key={selected.id+selected.version} job={selected} jobs={jobs} isNew={false} onDirty={()=>setDirty(true)} onSave={save}/>}</SheetContent></Sheet>
<AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Discard unsaved changes?</AlertDialogTitle><AlertDialogDescription>Save your changes before leaving to keep them.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep editing</AlertDialogCancel><AlertDialogAction onClick={()=>{setDirty(false);setCapture(null);setSelected(null);}}>Discard changes</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog><Toaster richColors position="top-center"/></SidebarProvider>;
}
const stepNames=['Save job','Check requirements','Prepare documents','Apply','Track response'];
function stage(j:Job){if(['Submitted','Waiting for Recommendation','Interview','Offer'].includes(j.status))return 5;const p=documentProgress(j);return p.unchecked?2:p.done<p.total?3:4;}
function actionLabel(j:Job){return stage(j)===5?(j.status==='Waiting for Recommendation'?'Waiting for recommendation':j.status==='Submitted'?'Track response':j.status==='Interview'?'Track interview':'Review offer'):stage(j)===2?'Check requirements':stage(j)===3?nextStep(j):'Submit application';}
function urgency(j:Job){if(!needsApplication(j)||!j.deadline)return 'normal';const d=daysLeft(j.deadline);return d<0?'overdue':d<=2?'critical':d<=7?'urgent':d<=21?'warning':'normal';}
function Due({job}:{job:Job}){if(!job.deadline)return <span className="due neutral">No deadline</span>;if(!needsApplication(job))return <span className="due neutral">{job.status}</span>;const n=daysLeft(job.deadline);return <span className={'due '+urgency(job)}>{n<0?Math.abs(n)+' days overdue':n===0?'Due today':n===1?'Due tomorrow':n+' days left'}</span>;}
function DocsProgress({job}:{job:Job}){const p=documentProgress(job);return <div className="doc-progress"><span>{p.total?p.done+' / '+p.total+' complete':p.unchecked?'Not checked':'No documents required'}</span>{p.total>0&&<Progress value={p.done/p.total*100}/>} {p.unchecked&&p.total>0&&<small>Requirements unchecked</small>}</div>;}
function nextStep(j:Job){if(documentProgress(j).unchecked)return 'Check requirements';const n=docNames.find(n=>['Required','In progress'].includes(j.docs[n]));return n?'Prepare '+n:'Documents complete';}
function AppNavigation({view,count,onNavigate}:{view:string;count:number;onNavigate:(name:string)=>void}){const {setOpenMobile}=useSidebar();return <SidebarMenu>{sections.map(({name,icon:Icon})=><SidebarMenuItem key={name}><SidebarMenuButton isActive={view===name} className="nav-item" onClick={()=>{onNavigate(name);setOpenMobile(false);}}><Icon/><span>{name}</span>{name==='Applications'&&<small>{count}</small>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu>;}
type SortKey='title'|'status'|'deadline'|'next'|'documents'|'location'|'country'|'type'|'salary'|'salarySource';
type GroupKey='none'|'status'|'step'|'country'|'deadline';
type ColumnKey='status'|'deadline'|'next'|'documents'|'location'|'country'|'type'|'salary'|'salarySource';
const columnOptions:{key:ColumnKey;label:string}[]=[{key:'status',label:'Status'},{key:'salary',label:'Net salary'},{key:'salarySource',label:'Salary source'},{key:'deadline',label:'Deadline'},{key:'next',label:'Next step'},{key:'documents',label:'Documents'},{key:'location',label:'Location'},{key:'country',label:'Country'},{key:'type',label:'Type'}];
function compareJobs(a:Job,b:Job,key:SortKey){if(key==='salary'){const sa=a.salaryDetails||extractText('Net salary: '+a.salary).salary,sb=b.salaryDetails||extractText('Net salary: '+b.salary).salary;const na=sa&&monthlyNet(sa),nb=sb&&monthlyNet(sb);if(!na||!nb)return !na&&!nb?0:!na?1:-1;return sa!.currency.localeCompare(sb!.currency)||na.min-nb.min;}const p=(j:Job)=>documentProgress(j);const value=(j:Job)=>key==='salarySource'?salarySource(j):key==='title'?j.title||j.organization:key==='status'?j.status:key==='deadline'?j.deadline||'9999-12-31':key==='next'?actionLabel(j):key==='documents'?p(j).total?String(p(j).done).padStart(3,'0')+'/'+String(p(j).total).padStart(3,'0'):p(j).unchecked?'000/999':'999/999':String(j[key]||'');return value(a).localeCompare(value(b),undefined,{numeric:true,sensitivity:'base'});}
function groupJobs(rows:Job[],key:GroupKey){if(key==='none')return {'All applications':rows};return rows.reduce<Record<string,Job[]>>((groups,j)=>{const label=key==='status'?j.status:key==='step'?actionLabel(j):key==='country'?j.country||'Country not set':urgency(j)==='overdue'?'Overdue':urgency(j)==='critical'?'Due in 2 days':urgency(j)==='urgent'?'Due this week':urgency(j)==='warning'?'Due in 3 weeks':j.deadline?'Later':'No deadline';(groups[label]??=[]).push(j);return groups;},{});}
function SortHead({label,sortKey,sort,setSort}:{label:string;sortKey:SortKey;sort:{key:SortKey;direction:'asc'|'desc'};setSort:any}){const active=sort.key===sortKey;return <TableHead><button className={'sort-head '+(active?'active':'')} onClick={()=>setSort((current:{key:SortKey;direction:'asc'|'desc'})=>current.key===sortKey?{key:sortKey,direction:current.direction==='asc'?'desc':'asc'}:{key:sortKey,direction:'asc'})}>{label}{active?(sort.direction==='asc'?<ChevronUp/>:<ChevronDown/>):<ArrowUpDown/>}</button></TableHead>;}
function ApplicationRow({job:j,columns,openJob}:{job:Job;columns:Record<ColumnKey,boolean>;openJob:(j:Job)=>void}){return <TableRow className={'application-row '+urgency(j)}><TableCell><button className="job-title" onClick={()=>openJob(j)}><span className="org-icon">{(j.organization||j.title||'Job').slice(0,2).toUpperCase()}</span><span><strong>{j.title||'Saved posting'}</strong><small>{j.organization||'Organization not added'}{j.location?' · '+j.location:''}</small><span className="mobile-due"><Due job={j}/></span></span></button></TableCell>{columns.status&&<TableCell><span className={'status '+j.status.toLowerCase().replaceAll(' ','-')}><i/>{j.status}</span></TableCell>}{columns.deadline&&<TableCell><span className="deadline-cell">{dateLabel(j.deadline)}</span>{needsApplication(j)&&<Due job={j}/>}</TableCell>}{columns.salary&&<TableCell>{j.salary||"—"}</TableCell>}{columns.salarySource&&<TableCell><span className="salary-source">{salarySource(j)}</span></TableCell>}{columns.next&&<TableCell>{closed(j)?<span className="muted">Closed</span>:<span className="table-next">{actionLabel(j)}</span>}</TableCell>}{columns.documents&&<TableCell><DocsProgress job={j}/></TableCell>}{columns.location&&<TableCell>{j.location||'—'}</TableCell>}{columns.country&&<TableCell>{j.country||'—'}</TableCell>}{columns.type&&<TableCell>{j.type||'—'}</TableCell>}<TableCell><button className="icon-button" aria-label={'Edit '+(j.title||'saved posting')} onClick={()=>openJob(j)}><ArrowUpRight size={18}/></button></TableCell></TableRow>;}
